global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 5s # Ждем 5 секунд перед отправкой группы
  group_interval: 5s
  repeat_interval: 15s # Если проблема не решена, повторяем через 30 секунд
  receiver: 'smart-middleware'

receivers:
  - name: 'smart-middleware'
    webhook_configs:
      - url: 'http://middleware:8000/alert' # Шлем в твой Python код
        send_resolved: true # Шлем и при пропадании проблемы