global:
  scrape_interval: 5s # Чаще опрашиваем для демонстрации
  evaluation_interval: 5s # Чаще проверяем правила

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'spb_server'
    static_configs:
      - targets: ['spb:9100'] # Обращаемся по имени контейнера